# Generated by Django 3.2.6 on 2021-11-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purse',
            old_name='product_available',
            new_name='book_available',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
